version: '2.0'
services:
  pulsar:
    image: apachepulsar/pulsar
    ports: 
      - "8080:8080"
      - "6650:6650"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
  pulsar-dashboard:
    image: apachepulsar/pulsar-dashboard
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://pulsar:8080
networks:
  default: 
    driver: bridge