version: '2.0'
services:
  pulsar:
    image: apachepulsar/pulsar-all
    ports: 
      - "8080:8080"
      - "6650:6650"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

  cassandra:
    build: ./infrastructure/cassandra/src/
    # image: cassandra:latest
    environment:
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
    ports: 
      - "7000:7000"
      - "9042:9042"
networks:
  default: 
    driver: bridge