
namePrefix: flink-
namespace: iot-prototype
commonLabels:
  service: flink


resources:
  - config/configuration-configmap.yaml
  - jobmanager/deployment.yaml
  - jobmanager/rest-service.yaml
  - jobmanager/service.yaml
  - taskmanager/deployment.yaml