cluster: 
  replicaCount: 1
  seedCount: 1
persistence: 
  enabled: false
dbUser:
  user: cassandra
  password: cassandra

resources: 
  limits: 
    memory: "4000Mi"
  requests: 
    memory: "1000Mi"