cluster: 
  replicaCount: 3
  seedCount: 3
persistence: 
  enabled: false
dbUser:
  user: cassandra
  password: cassandra


resources: 
  limits: 
    memory: "10000Mi"
  requests: 
    memory: "3000Mi"